### ISSUE TITLE
Graphic not saved to disk

### ISSUE THREAD

**Issue by mankoff** [gregsexton/ob-ipython#12] opened 2015-06-15 15:49 UTC
Just found `ob-ipython` and I'm thrilled to see improved IPython support in Org.

I'm working my way through the README and most things work as expected, but not the image example. The `#+RESULTS:` line shows a link to whatever filename I enter in the `:file foo.png` header command. But the file does not appear on disk nor does it display in the Org buffer.

I'm on OS X 10.10.3 and using a recent emacs from Homebrew.

**Comment by mankoff** [comment] 2015-06-15 16:56
A bit more detail - after running the example in the README, a buffer does exist with the full pathname as specified in the `:file` header argument. But it is not written to disk. Emacs then prompts (every time),

    Buffer foo.png modified; kill anyway? (y or n)

**Comment by deprecated** [comment] 2015-06-17 05:21
I have exactly the same issue.  Here is what is written to the `*Messages*` buffer:
```
executing Ipython code block...
Contacting host: localhost:9988
Type C-c C-c to view the image as text.
Saving file /tmp/image.png...
eq: Text is read-only
```
I too get the confirmation dialogue, asking if I want to kill the buffer.  Even though I have set `debug-on-error` I don't seem to get any traceback. 

Also on OS X 10.10.3, using the latest Emacs Mac Port from homebrew cask:
```
#+BEGIN_SRC emacs-lisp
(emacs-version)
#+END_SRC

#+RESULTS:
: GNU Emacs 24.5.4 (x86_64-apple-darwin13.4.0, Carbon Version 157 AppKit 1265.21)
:  of 2015-05-17 on Atago.local

#+BEGIN_SRC emacs-lisp
(org-version)
#+END_SRC

#+RESULTS:
: 8.2.10
```

**Comment by deprecated** [comment] 2015-06-17 15:31
Applying pull request #3 from @njg fixed this issue for me with my usual emacs configuration. 

On the other hand, I tried it with a vanilla configuration and everything works fine out of the box.  That is, it was *not* necessary to apply the `with-silent-modifications` patch.  So it must be a bad interaction with one of the other packages that I load.  However, there are 108 of those and I don't have the energy to brute-force bisect the issue at the moment.  Maybe at the weekend ...

**Comment by gregsexton** [comment] 2015-06-24 19:28
Thanks for raising this and letting me know that it works in a vanilla install. If you can provide further info that would be great. I can't reproduce this.

**Comment by mankoff** [comment] 2015-06-24 20:19
That was an annoying binary search through a 2500 line init file, but the issue seems to be:

```elisp
(setq require-final-newline t)
```
Removing this makes IPython-mode graphics work for me.

**Comment by gregsexton** [comment] 2015-06-27 12:01
Thanks a lot for figuring this out. I'll see what I can do.

**Comment by gregsexton** [comment] 2015-06-27 12:09
Just pushed a fix.

**Closed** 2015-06-27 12:08 UTC
Labels: bug

**Comment by mhlr** [comment] 2016-03-01 20:53
I am seeing this issue again in emacs 25 with org 8.3


#+BEGIN_SRC emacs-lisp
(emacs-version)
#+END_SRC

#+RESULTS:
: GNU Emacs 25.1.50.2 (x86_64-pc-linux-gnu, GTK+ Version 3.10.8)
:  of 2016-02-19

#+BEGIN_SRC emacs-lisp
(org-version)
#+END_SRC

#+RESULTS:
: 8.3.4
